# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'iOS Text Reminder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Text Reminder
  pod 'Alamofire', '~> 4.7'
  target 'iOS Text ReminderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS Text ReminderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
